language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t tfelixti/fibo-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tfelixti/fibo-test npm run test

after_success:
  - docker build -t tfelixti/fibo-client ./client
  - docker build -t tfelixti/fibo-nginx ./nginx
  - docker build -t tfelixti/fibo-server ./server
  - docker build -t tfelixti/fibo-worker ./worker
  # Log in to the Docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push tfelixti/fibo-client
  - docker push tfelixti/fibo-nginx
  - docker push tfelixti/fibo-server
  - docker push tfelixti/fibo-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: fibo-app
  env: FiboApp-env
  bucket_name: elasticbeanstalk-us-east-2-801040296118
  bucket_path: fibo-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

