language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t tfelix/fibo-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tfelix/fibo-test npm test

after_success:
  - docker build -t tfelix/fibo-client ./client
  - docker build -t tfelix/fibo-nginx ./nginx
  - docker build -t tfelix/fibo-server ./server
  - docker build -t tfelix/fibo-worker ./worker
  # Log in to the Docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push tfelix/fibo-client
  - docker push tfelix/fibo-nginx
  - docker push tfelix/fibo-server
  - docker push tfelix/fibo-worker
